[package]
name = "conn-table"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tricky-pipe = { path = "../tricky-pipe" }
tracing = { version = "0.1.21", default-features = false }