[profile.loom]
slow-timeout = { period = "10m" }
fail-fast = false

[profile.ci]
slow-timeout = { period = "60s", terminate-after = 2 }
fail-fast = false
retries = 2

[profile.miri]
slow-timeout = { period = "3m" }
fail-fast = false
