[package]
name = "tricky-pipe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maitake-sync = "0.1.0"
portable-atomic = "1.4.3"

[dependencies.postcard]
version = "1.0.7"
features = ["use-std"]

[dependencies.serde]
version = "1.0.188"
features = ["derive"]

[dependencies.plugtail]
path = "../plugtail"
